### ISSUE TITLE
Problem with stickers parsing

### ISSUE THREAD

**Issue by Timos741** [superhe11/csgo-price-parcer#1]
Hello, I don’t understand how to add a new type of items (stickers) and a list of items whose prices I need to find.

**Comment by superhe11** [comment]
Hey, now parcer only parse gloves/knifes because it's most profitable items, in a couple of days I will add all stickers as well

**Comment by superhe11** [comment]
Now you can write in script "stickers" to parce stickers from market, or you can add links from items you want to parce in items.txt to parce prices from that urls.
